import { useEffect, useState } from 'react';
import { dataService } from '../../services/dataService';
import { useAuthStore } from '../../store/authStore';
import { useLiveSessionStore } from '../../store/liveSessionStore';
import { PageHeader } from '../../components/ui/PageHeader';
import { Card } from '../../components/ui/Card';
import { LiveLineChart } from '../../components/charts/SimpleCharts';
import { ChartCard } from '../../components/ui/ChartCard';
import { AlertsPanel, ClassMetrics, RobotControl, ScenarioController, SessionHeader, StudentFocus, StudentsGrid, Timeline } from '../../components/teacher/LiveSessionParts';
export default function TeacherLiveSession(){ const {user}=useAuthStore(); const st=useLiveSessionStore(); const [classes,setClasses]=useState([]); const [students,setStudents]=useState([]); const [selectedClassId,setSelectedClassId]=useState(''); useEffect(()=>{dataService.getClassesForTeacher(user.id).then(c=>{setClasses(c);setSelectedClassId(c[0]?.id)});},[user.id]); useEffect(()=>{ if(selectedClassId) dataService.getStudentsByClass(selectedClassId).then(setStudents); },[selectedClassId]); const start=()=>{const c=classes.find(x=>x.id===selectedClassId); st.startSession({classId:selectedClassId,className:c?.name,teacherId:user.id,students});}; return <div className="grid"><PageHeader title="Live Class Session" subtitle="Real-time monitoring and smart support"/><SessionHeader classes={classes} selectedClassId={selectedClassId} setSelectedClassId={setSelectedClassId} onStart={start}/><ScenarioController students={students}/><ClassMetrics/><div className="grid" style={{gridTemplateColumns:'2fr 1.05fr'}}><ChartCard title="Class Trends" subtitle="Live attention, engagement, and stress signals" actions={<><span className="badge blue">Attention</span><span className="badge green">Engagement</span><span className="badge orange">Stress</span></>}><LiveLineChart data={st.metricHistory}/></ChartCard><AlertsPanel/></div><div className="grid" style={{gridTemplateColumns:'2fr 1fr'}}><StudentsGrid/><RobotControl/></div><div className="grid" style={{gridTemplateColumns:'1.1fr 1fr'}}><StudentFocus/><Card><h2 style={{marginTop:0}}>Robot Status</h2><div style={{display:'flex',gap:14,alignItems:'center'}}><div className="robot-face status-pulse"/><div><div className="small muted">Current mode</div><h2 style={{margin:'5px 0',fontSize:22}}>{st.robotState.mode}</h2><p className="muted">Target: {st.robotState.target}<br/>Effect: {st.robotState.effect}</p></div></div></Card></div><Timeline/></div> }
