import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip, CartesianGrid, BarChart, Bar, RadialBarChart, RadialBar, Legend } from 'recharts';
import { useI18n } from '../../i18n';
const axis = { fontSize: 11, fill: '#64748B', fontWeight: 700 };
const tooltip = { backgroundColor: '#FFFFFF', border: '1px solid #D7EAF4', borderRadius: 12, boxShadow: '0 18px 40px rgba(13,43,87,.12)', color: '#0D2B57' };
const legendStyle = { fontSize: 12, fontWeight: 800, color: '#163B66' };
const metricLabel = (t, value) => t(value.charAt(0).toUpperCase() + value.slice(1));
export function LiveLineChart({data, height=220}){ const {t}=useI18n(); return <ResponsiveContainer width="100%" height={height}><LineChart data={data} margin={{top:10,right:12,left:-16,bottom:0}}><CartesianGrid stroke="#EAF1F6" strokeDasharray="3 4" vertical={false}/><XAxis dataKey="time" tick={axis} axisLine={false} tickLine={false} tickFormatter={value => t(value)}/><YAxis domain={[0,100]} tick={axis} axisLine={false} tickLine={false}/><Tooltip contentStyle={tooltip} labelFormatter={value => t(value)} formatter={(value, name) => [value, metricLabel(t, String(name))]}/><Legend wrapperStyle={legendStyle} iconType="circle"/><Line name={t('Attention')} type="monotone" dataKey="attention" stroke="#38AEEA" strokeWidth={2.4} dot={false} activeDot={{r:4}}/><Line name={t('Engagement')} type="monotone" dataKey="engagement" stroke="#16A36A" strokeWidth={2.4} dot={false} activeDot={{r:4}}/><Line name={t('Stress')} type="monotone" dataKey="stress" stroke="#F59E0B" strokeWidth={2.4} dot={false} activeDot={{r:4}}/></LineChart></ResponsiveContainer> }
export function MiniLineChart({data,height=82}){ const {t}=useI18n(); return <ResponsiveContainer width="100%" height={height}><LineChart data={data} margin={{top:6,right:2,left:2,bottom:2}}><Tooltip contentStyle={tooltip} labelFormatter={value => t(value)} formatter={(value, name) => [value, metricLabel(t, String(name))]}/><Line type="monotone" dataKey="attention" stroke="#38AEEA" dot={false} strokeWidth={2}/><Line type="monotone" dataKey="stress" stroke="#F59E0B" dot={false} strokeWidth={2}/></LineChart></ResponsiveContainer> }
export function StudentsBarChart({data}){ const {t}=useI18n(); return <ResponsiveContainer width="100%" height={250}><BarChart data={data} margin={{top:10,right:8,left:-12,bottom:0}}><CartesianGrid stroke="#EAF1F6" strokeDasharray="3 4" vertical={false}/><XAxis dataKey="name" tick={axis} axisLine={false} tickLine={false} tickFormatter={value => t(value)}/><YAxis domain={[0,100]} tick={axis} axisLine={false} tickLine={false}/><Tooltip contentStyle={tooltip} labelFormatter={value => t(value)} formatter={(value, name) => [value, metricLabel(t, String(name))]}/><Legend wrapperStyle={legendStyle} iconType="circle"/><Bar name={t('Attention')} dataKey="attention" fill="#38AEEA" radius={[6,6,0,0]}/><Bar name={t('Engagement')} dataKey="engagement" fill="#16A36A" radius={[6,6,0,0]}/><Bar name={t('Stress')} dataKey="stress" fill="#F59E0B" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer> }
export function WellbeingGauge({value=82}){ const {t}=useI18n(); const data=[{name:t('Wellbeing'), value, fill:value>70?'#16A36A':'#F59E0B'}]; return <ResponsiveContainer width="100%" height={150}><RadialBarChart innerRadius="72%" outerRadius="100%" data={data} startAngle={90} endAngle={-270}><RadialBar dataKey="value" cornerRadius={20}/><Legend iconSize={0} formatter={()=><span style={{fontWeight:900,color:'#0D2B57',fontSize:23}}>{value}%</span>} /></RadialBarChart></ResponsiveContainer> }
